### ISSUE TITLE
Normalize method naming/behavior

### ISSUE THREAD

**Issue by austinglaser** [Michael-F-Bryan/const-arrayvec#1]
I like the distinction between `try_insert()` and `insert()`. Along those lines, would it make sense for the current `push()` to become `try_push()`, and implement `push()` something like the below?

```rust
pub fn push(&mut self, item: T) {
    match self.try_push(item) {
        Ok(_) => {},
        Err(e) => panic!("Push failed: {}", e),
    }
}
```

**Comment by Michael-F-Bryan** [comment]
Good point! It looks like that's the approach [`arrayvec` takes](https://docs.rs/arrayvec/0.5.1/arrayvec/struct.ArrayVec.html#method.push). I'll update the crate and blog post accordingly.
