### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by burdges** [Michael-F-Bryan/const-arrayvec#5]
Is there some reason why `<T, const N: usize>` might be preferable to `<[T; N]>`?  If const generics worked, then anything doable with the former should already be doable with `[T; N]`, no?  And `[T; N]` works out more ergonomic normally, no?

**Comment by Michael-F-Bryan** [comment]
Have you read [the accompanying blog post](http://adventures.michaelfbryan.com/posts/const-arrayvec/)? This was mainly intended as an experiment with const generics.

> And `[T; N]` works out more ergonomic normally, no?

I don't agree with you there, `ArrayVec<T, N>` has a lot less syntactic noise than `ArrayVec<[T; N]>`.

>  If const generics worked, then anything doable with the former should already be doable with `[T; N]`, no?

You can't declare a type to be generic over `[T; N]`, so this would be invalid syntax:

```rust
struct ArrayVec<[T; N]> { ... }
```

Meaning you'd need to be generic over some trait that is implemented for all arrays (kinda like [`arrayvec::Array`](https://docs.rs/arrayvec/0.5.1/arrayvec/trait.Array.html)).

For example,

```rust
pub trait Array<T> {
    pub const LEN: usize;

    ...
}
```

The only way to access the array's length would be with something like `<A as Array<T>>::LEN`, which is a lot more clunky than just writing `N`.

Also, you'll notice that Rust's const generics take a lot of inspiration from C++ templates. If you were writing the equivalent in C++ it'd look something like this:

```cpp
template<typename T, size_t N>
class ArrayVec {  ... };
```

You *could* try to be generic over some array `T[N]` and use `sizeof(T[N]) / sizeof(T)`, but that's not idiomatic and would just be a pain.

I feel like "idiomatic" Rust would take the same approach... If you are generic over length, just add a type parameter for it.

---

Also, please note that it's often considered rude to make an issue against a project you've never contributed to questioning the meaning of its existence...

**Comment by burdges** [comment]
Apologies for the brief title.  I was genuinely curious because generic array gets used *lots* when a simple associated type works better. 

> `ArrayVec<T, N>` has a lot less syntactic noise than `ArrayVec<[T; N]>`.

Those two fewer symbols make no difference, and `<T, N>` gives the reader less information than `<[T; N]>`, but whatever.  

> You can't declare a type to be generic over `[T; N]`.

This is true.  Yes, you commonly want a type generic over `[T; N]`, but you'll never need a type generic over `[T; N]` only.  Anything like `struct ArrayWrapper<T,N>([Wrapper<T>; N])` might work too, provided it satisfies appropriate traits.   I think the real issues is:  What traits?  How do they handle `MaybeUninit<..>`?  etc.  I suspect `MaybeUninit` might require different handling for `ArrayWrapper` and `&mut [T]`, maybe making one arrayvec-like crate that fills all niches impossible, not sure.

Yes `size_of(A)/size_of(T)` would become awkward, not inside one crate, but externally yes.  `ArrayVec` introduces a new [`Array`](https://docs.rs/arrayvec/0.5.1/arrayvec/trait.Array.html) trait for this, mainly due to being written before `size_of(A)/size_of(T)` worked.  Almost any trait bound provides some ergonomic length function, but which one?  

All these trait questions belong on discord forums, not this repo or issue.  Thanks for your time!  :)
